set_property PACKAGE_PIN D18 [get_ports CK_P]
set_property PACKAGE_PIN C19 [get_ports CK_N]
set_property IOSTANDARD LVDS_25 [get_ports {CK_P CK_N}]
create_clock -name sys_clk -period 5.000 [get_ports CK_P]

set_property PACKAGE_PIN G19 [get_ports S_RESET]
set_property IOSTANDARD LVCMOS25 [get_ports S_RESET]

set_property PACKAGE_PIN E15 [get_ports {Led[0]}]
set_property PACKAGE_PIN D15 [get_ports {Led[1]}]
set_property PACKAGE_PIN W17 [get_ports {Led[2]}]
set_property PACKAGE_PIN W5  [get_ports {Led[3]}]
set_property PACKAGE_PIN V7  [get_ports {Led[4]}]
set_property PACKAGE_PIN W10 [get_ports {Led[5]}]
set_property PACKAGE_PIN P18 [get_ports {Led[6]}]
set_property PACKAGE_PIN P17 [get_ports {Led[7]}]

set_property IOSTANDARD LVCMOS25 [get_ports {Led[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Led[7]}]
